# MPLAB IDE generated this makefile for use with GNU make.
# Project: USB Device - WinUSB - Generic Driver - C30.mcp
# Date: Thu May 16 16:47:11 2013

AS = pic30-as.exe
CC = pic30-gcc.exe
LD = pic30-ld.exe
AR = pic30-ar.exe
HX = pic30-bin2hex.exe
RM = rm

USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30.hex : USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30.cof
	$(HX) "USB Device - WinUSB - Generic Driver - C30.cof"

USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30.cof : Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/main.o Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/usb_descriptors.o Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/usb_device.o Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/usb_function_generic.o
	$(CC) -mcpu=24FJ256GB106 "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\main.o" "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_descriptors.o" "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_device.o" "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_function_generic.o" -o"USB Device - WinUSB - Generic Driver - C30.cof" -Wl,-L"C:\Program Files\Microchip\MPLAB C30\lib",-Tp24FJ256GB106.gld,--defsym=__MPLAB_BUILD=1,--heap=800,-Map="USB Device - WinUSB - Generic Driver - C30.map",--report-mem

Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/main.o : usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/GenericTypeDefs.h USB/usb_function_generic.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_device.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_hal.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_ch9.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_common.h USB/usb.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal_pic24.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/GenericTypeDefs.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/limits.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_common.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_ch9.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h USB/usb_device.h GenericTypeDefs.h HardwareProfile\ -\ PIC24F\ Starter\ Kit.h HardwareProfile.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/string.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdlib.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/yvals.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdio.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24FJ256GB106.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24Fxxxx.h Compiler.h main.c
	$(CC) -mcpu=24FJ256GB106 -x c -c "main.c" -o"./Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\main.o" -I"..\..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." -g -Wall

Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/usb_descriptors.o : ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal_pic24.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/GenericTypeDefs.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/limits.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_common.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_ch9.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h USB/usb_device.h usb_config.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/string.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdlib.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/yvals.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdio.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24FJ256GB106.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24Fxxxx.h Compiler.h GenericTypeDefs.h usb_descriptors.c
	$(CC) -mcpu=24FJ256GB106 -x c -c "usb_descriptors.c" -o"./Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_descriptors.o" -I"..\..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." -g -Wall

Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/usb_device.o : usb_config.h HardwareProfile\ -\ PIC24F\ Starter\ Kit.h HardwareProfile.h USB/usb_device.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_ch9.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_device.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal_pic24.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_common.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_hal.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_ch9.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/GenericTypeDefs.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/limits.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb/usb_common.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h USB/USB.h USB/usb_ch9.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/string.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdlib.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/yvals.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdio.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24FJ256GB106.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24Fxxxx.h Compiler.h GenericTypeDefs.h usb_device.c
	$(CC) -mcpu=24FJ256GB106 -x c -c "usb_device.c" -o"./Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_device.o" -I"..\..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." -g -Wall

Objects/USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ -\ C30\ -\ PIC24FJ256GB110\ PIM/usb_function_generic.o : ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal_pic24.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/usb_config.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/GenericTypeDefs.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/limits.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_common.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_hal.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/USB/usb_ch9.h ../../USB\ Device\ -\ WinUSB\ -\ Generic\ Driver\ Demo/WinUSB\ Simple\ Demo\ -\ Firmware/Compiler.h USB/usb_device.h usb_config.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/string.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdlib.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/yvals.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/include/stdio.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24FJ256GB106.h c:/microchip\ starter\ kits/pic24f\ starter\ kit\ 1/mplab\ c30/support/PIC24F/h/p24Fxxxx.h Compiler.h GenericTypeDefs.h usb_function_generic.c
	$(CC) -mcpu=24FJ256GB106 -x c -c "usb_function_generic.c" -o"./Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_function_generic.o" -I"..\..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\USB Device - WinUSB - Generic Driver Demo\WinUSB Simple Demo - Firmware" -I"..\..\Microchip\Include" -I"..\..\..\Include" -I"..\..\Include" -I"." -g -Wall

clean : 
	$(RM) "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\main.o" "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_descriptors.o" "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_device.o" "Objects\USB Device - WinUSB - Generic Driver - C30 - PIC24FJ256GB110 PIM\usb_function_generic.o" "USB Device - WinUSB - Generic Driver - C30.cof" "USB Device - WinUSB - Generic Driver - C30.hex"

